# Generated by Django 2.2.7 on 2020-01-17 16:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20200107_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Headache'), (2, 'Earache'), (3, 'Bodyache')], max_length=4),
        ),
    ]
