# Generated by Django 2.2.7 on 2020-01-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20200121_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='my_field2',
            new_name='Symptoms',
        ),
    ]
